### ISSUE TITLE
Crashed on startup

### ISSUE THREAD

**Issue by KunNiu** [Shopify/mobile-buy-android-sample#17]
Crash happened after provide my own credentials
```
java.lang.NullPointerException: Attempt to invoke virtual method 'com.shopify.buy3.Storefront$Shop com.shopify.buy3.Storefront$QueryRoot.getShop()' on a null object reference
                 	at com.shopify.sample.domain.usecases.FetchCollectionsUseCaseImpl.lambda$execute$7(FetchCollectionsUseCaseImpl.java:52)
                 	at com.shopify.sample.domain.usecases.-$$Lambda$FetchCollectionsUseCaseImpl$i44dMPEfUSM1FloXC8d1zqj8mcQ.invoke(Unknown Source:4)
                 	at com.shopify.buy3.internal.RetryableGraphHttpCall$dispatch$$inlined$also$lambda$1.run(RealGraphCall.kt:283)
                 	at android.os.Handler.handleCallback(Handler.java:942)
                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                 	at android.os.Looper.loopOnce(Looper.java:201)
                 	at android.os.Looper.loop(Looper.java:288)
                 	at android.app.ActivityThread.main(ActivityThread.java:7884)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by FathyHafy** [comment]
Did you use store front access token or API key from Sopyfy admin

**Comment by readelobdill** [comment]
Getting the same with default credentials on Android Studio Giraffe

```
SHOP_DOMAIN=graphql.myshopify.com
API_KEY=8e2fef6daed4b93cf4e731f580799dd1
```
