### ISSUE TITLE
App Not Working

### ISSUE THREAD

**Issue by svpn** [Shopify/mobile-buy-android-sample#8]
After launching the app in AVD the app shows "Oops, something went wrong please try again".

In Android Studio the following error message is displayed at the bottom the logs window:

E/BaseApplication: Failed to fetch shop settings
    com.shopify.buy3.GraphError$HttpError: HTTP(403) 
        at com.shopify.buy3.internal.HttpResponseParser.successResponse(HttpResponseParser.kt:55)
        at com.shopify.buy3.internal.HttpResponseParser.parse(HttpResponseParser.kt:42)
        at com.shopify.buy3.internal.GraphHttpResultCallback.parse(RealGraphCall.kt:332)
        at com.shopify.buy3.internal.GraphHttpResultCallback.onResponse(RealGraphCall.kt:311)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)

**Comment by svpn** [comment]
I've also posted this to the forum here:

https://community.shopify.com/c/Shopify-APIs-SDKs/Mobile-Buy-SDK-Sample-Android-App-Not-working/m-p/826114#M53638

**Comment by Jigneshjagad** [comment]
> I've also posted this to the forum here:
> 
> https://community.shopify.com/c/Shopify-APIs-SDKs/Mobile-Buy-SDK-Sample-Android-App-Not-working/m-p/826114#M53638

check my post may it will help to resolve your issue 

https://community.shopify.com/c/Shopify-APIs-SDKs/Mobile-Buy-SDK-Sample-Android-App-Not-working/m-p/891531/highlight/true#M56601
